namespace NohaFMS.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class pendingmigrationmssql : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.SecurityGroup_User", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.SecurityGroup_User", "UserId", "dbo.User");
            DropForeignKey("dbo.Assignment_User", "AssignmentId", "dbo.Assignment");
            DropForeignKey("dbo.Assignment_User", "UserId", "dbo.User");
            DropForeignKey("dbo.Site_Address", "SiteId", "dbo.Site");
            DropForeignKey("dbo.Site_Address", "AddressId", "dbo.Address");
            DropForeignKey("dbo.Site_SecurityGroup", "SiteId", "dbo.Site");
            DropForeignKey("dbo.Site_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.Organization_Address", "OrganizationId", "dbo.Organization");
            DropForeignKey("dbo.Organization_Address", "AddressId", "dbo.Address");
            DropForeignKey("dbo.SecurityGroup_PermissionRecord", "PermissionRecordId", "dbo.PermissionRecord");
            DropForeignKey("dbo.SecurityGroup_PermissionRecord", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.Report_SecurityGroup", "ReportId", "dbo.Report");
            DropForeignKey("dbo.Report_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.Visual_SecurityGroup", "VisualId", "dbo.Visual");
            DropForeignKey("dbo.Visual_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.Company_Address", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Company_Address", "AddressId", "dbo.Address");
            DropForeignKey("dbo.PM_MeterEvent", "PreventiveMaintenanceId", "dbo.PreventiveMaintenance");
            DropForeignKey("dbo.PM_MeterEvent", "MeterEventId", "dbo.MeterEvent");
            DropForeignKey("dbo.Team_Technician", "TeamId", "dbo.Team");
            DropForeignKey("dbo.Team_Technician", "TechnicianId", "dbo.Technician");
            DropForeignKey("dbo.ActivityLog", "UserId", "dbo.User");
            AlterColumn("dbo.Address", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Address", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetDowntime", "StartDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetDowntime", "EndDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetDowntime", "ReportedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetDowntime", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetDowntime", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Asset", "InstallationDate", c => c.DateTime());
            AlterColumn("dbo.Asset", "WarrantyStartDate", c => c.DateTime());
            AlterColumn("dbo.Asset", "WarrantyEndDate", c => c.DateTime());
            AlterColumn("dbo.Asset", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Asset", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetLocationHistory", "ChangedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetLocationHistory", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetLocationHistory", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.User", "PasswordSalt", c => c.String());
            AlterColumn("dbo.User", "DateOfBirth", c => c.DateTime());
            AlterColumn("dbo.User", "PasswordLastChanged", c => c.DateTime());
            AlterColumn("dbo.User", "BannedDateFrom", c => c.DateTime());
            AlterColumn("dbo.User", "LastLoginTime", c => c.DateTime());
            AlterColumn("dbo.User", "LastApiRequest", c => c.DateTime());
            AlterColumn("dbo.User", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.User", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Assignment", "ExpectedStartDateTime", c => c.DateTime());
            AlterColumn("dbo.Assignment", "DueDateTime", c => c.DateTime());
            AlterColumn("dbo.Assignment", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Assignment", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Site", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Site", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Organization", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Organization", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.SecurityGroup", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.SecurityGroup", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PermissionRecord", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PermissionRecord", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Feature", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Feature", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.FeatureAction", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.FeatureAction", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Module", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Module", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Report", "Query", c => c.String());
            AlterColumn("dbo.Report", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Report", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ReportColumn", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ReportColumn", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ReportFilter", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ReportFilter", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Filter", "SqlQuery", c => c.String());
            AlterColumn("dbo.Filter", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Filter", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Visual", "Query", c => c.String());
            AlterColumn("dbo.Visual", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Visual", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.VisualFilter", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.VisualFilter", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Language", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Language", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.LocaleStringResource", "ResourceValue", c => c.String(nullable: false));
            AlterColumn("dbo.LocaleStringResource", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.LocaleStringResource", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.UserPasswordHistory", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.UserPasswordHistory", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.UserDevice", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.UserDevice", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Location", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Location", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ValueItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ValueItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ValueItemCategory", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ValueItemCategory", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetSparePart", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetSparePart", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Item", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Item", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ItemGroup", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ItemGroup", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Company", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Company", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Contact", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Contact", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Contract", "StartDate", c => c.DateTime());
            AlterColumn("dbo.Contract", "EndDate", c => c.DateTime());
            AlterColumn("dbo.Contract", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Contract", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ContractPriceItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ContractPriceItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ContractTerm", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ContractTerm", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PreventiveMaintenance", "FirstWorkExpectedStartDateTime", c => c.DateTime());
            AlterColumn("dbo.PreventiveMaintenance", "FirstWorkDueDateTime", c => c.DateTime());
            AlterColumn("dbo.PreventiveMaintenance", "EndDateTime", c => c.DateTime());
            AlterColumn("dbo.PreventiveMaintenance", "TempExpectedStartDateTime", c => c.DateTime());
            AlterColumn("dbo.PreventiveMaintenance", "TempWorkDueDateTime", c => c.DateTime());
            AlterColumn("dbo.PreventiveMaintenance", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PreventiveMaintenance", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Code", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Code", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.MeterEvent", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.MeterEvent", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Meter", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Meter", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.UnitOfMeasure", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.UnitOfMeasure", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.MeterEventHistory", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.MeterEventHistory", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Point", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Point", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.MeterGroup", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.MeterGroup", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.MeterLineItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.MeterLineItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PointMeterLineItem", "LastDateOfReading", c => c.DateTime());
            AlterColumn("dbo.PointMeterLineItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PointMeterLineItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Reading", "DateOfReading", c => c.DateTime());
            AlterColumn("dbo.Reading", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Reading", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrder", "RequestedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrder", "ExpectedStartDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrder", "DueDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrder", "OnSiteDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrder", "ActualStartDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrder", "ActualEndDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrder", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrder", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ServiceRequest", "RequestedDateTime", c => c.DateTime());
            AlterColumn("dbo.ServiceRequest", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ServiceRequest", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.TaskGroup", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.TaskGroup", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Task", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Task", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Store", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Store", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreLocator", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreLocator", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorItem", "BatchDate", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorItem", "ExpiryDate", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorItemLog", "BatchDate", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorItemLog", "TransactionDate", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorItemLog", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorItemLog", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderLabor", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderLabor", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Craft", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Craft", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Team", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Team", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Technician", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Technician", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Calendar", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Calendar", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.CalendarNonWorking", "NonWorkingDate", c => c.DateTime());
            AlterColumn("dbo.CalendarNonWorking", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.CalendarNonWorking", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Shift", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Shift", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ShiftPattern", "StartTime", c => c.DateTime());
            AlterColumn("dbo.ShiftPattern", "EndTime", c => c.DateTime());
            AlterColumn("dbo.ShiftPattern", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ShiftPattern", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderMiscCost", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderMiscCost", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderServiceItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderServiceItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ServiceItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ServiceItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderTask", "CompletedDate", c => c.DateTime());
            AlterColumn("dbo.WorkOrderTask", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkOrderTask", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMLabor", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMLabor", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMMeterFrequency", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMMeterFrequency", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMMiscCost", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMMiscCost", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMServiceItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMServiceItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMTask", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PMTask", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Currency", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Currency", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetStatusHistory", "ChangedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetStatusHistory", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssetStatusHistory", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Attribute", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Attribute", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.EntityAttribute", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.EntityAttribute", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AuditEntityConfiguration", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AuditEntityConfiguration", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AuditTrail", "Date", c => c.DateTime(nullable: false));
            AlterColumn("dbo.AuditTrail", "LogXml", c => c.String());
            AlterColumn("dbo.AuditTrail", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AuditTrail", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AutoNumber", "FormatString", c => c.String());
            AlterColumn("dbo.AutoNumber", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AutoNumber", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Attachment", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Attachment", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.EntityAttachment", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.EntityAttachment", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Comment", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Comment", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Picture", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Picture", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Message", "SentDateTime", c => c.DateTime());
            AlterColumn("dbo.Message", "Messages", c => c.String());
            AlterColumn("dbo.Message", "Subject", c => c.String());
            AlterColumn("dbo.Message", "Recipients", c => c.String());
            AlterColumn("dbo.Message", "CCRecipients", c => c.String());
            AlterColumn("dbo.Message", "RecipientNames", c => c.String());
            AlterColumn("dbo.Message", "CCRecipientNames", c => c.String());
            AlterColumn("dbo.Message", "Errors", c => c.String());
            AlterColumn("dbo.Message", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Message", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.MessageTemplate", "EmailBodyTemplate", c => c.String());
            AlterColumn("dbo.MessageTemplate", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.MessageTemplate", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Setting", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Setting", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.UserDashboard", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.UserDashboard", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.UserDashboardVisual", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.UserDashboardVisual", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ImportProfile", "EntityType", c => c.String());
            AlterColumn("dbo.ImportProfile", "LastRunStartDateTime", c => c.DateTime());
            AlterColumn("dbo.ImportProfile", "LastRunEndDateTime", c => c.DateTime());
            AlterColumn("dbo.ImportProfile", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ImportProfile", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorReservation", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.StoreLocatorReservation", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AdjustItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AdjustItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Adjust", "AdjustDate", c => c.DateTime());
            AlterColumn("dbo.Adjust", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Adjust", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PhysicalCount", "PhysicalCountDate", c => c.DateTime());
            AlterColumn("dbo.PhysicalCount", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PhysicalCount", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.PhysicalCountItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.PhysicalCountItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.IssueItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.IssueItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Issue", "IssueDate", c => c.DateTime());
            AlterColumn("dbo.Issue", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Issue", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ReceiptItem", "ExpiryDate", c => c.DateTime());
            AlterColumn("dbo.ReceiptItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ReceiptItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Receipt", "ReceiptDate", c => c.DateTime());
            AlterColumn("dbo.Receipt", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Receipt", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ReturnItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ReturnItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Return", "ReturnDate", c => c.DateTime());
            AlterColumn("dbo.Return", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Return", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.TransferItem", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.TransferItem", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Transfer", "TransferDate", c => c.DateTime());
            AlterColumn("dbo.Transfer", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Transfer", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.UnitConversion", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.UnitConversion", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ActivityLog", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ActivityLog", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.ActivityLogType", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.ActivityLogType", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Log", "ShortMessage", c => c.String(nullable: false));
            AlterColumn("dbo.Log", "FullMessage", c => c.String());
            AlterColumn("dbo.Log", "CreatedOnUtc", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Log", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Log", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.Script", "SourceCode", c => c.String());
            AlterColumn("dbo.Script", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.Script", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssignmentGroup", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssignmentGroup", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssignmentGroupUser", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssignmentGroupUser", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssignmentHistory", "ExpectedStartDateTime", c => c.DateTime());
            AlterColumn("dbo.AssignmentHistory", "DueDateTime", c => c.DateTime());
            AlterColumn("dbo.AssignmentHistory", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.AssignmentHistory", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkflowDefinition", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkflowDefinition", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkflowDefinitionVersion", "WorkflowXamlFileContent", c => c.String());
            AlterColumn("dbo.WorkflowDefinitionVersion", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkflowDefinitionVersion", "ModifiedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkflowInstance", "InstanceData", c => c.String());
            AlterColumn("dbo.WorkflowInstance", "CreatedDateTime", c => c.DateTime());
            AlterColumn("dbo.WorkflowInstance", "ModifiedDateTime", c => c.DateTime());
            AddForeignKey("dbo.SecurityGroup_User", "SecurityGroupId", "dbo.SecurityGroup", "Id");
            AddForeignKey("dbo.SecurityGroup_User", "UserId", "dbo.User", "Id");
            AddForeignKey("dbo.Assignment_User", "AssignmentId", "dbo.Assignment", "Id");
            AddForeignKey("dbo.Assignment_User", "UserId", "dbo.User", "Id");
            AddForeignKey("dbo.Site_Address", "SiteId", "dbo.Site", "Id");
            AddForeignKey("dbo.Site_Address", "AddressId", "dbo.Address", "Id");
            AddForeignKey("dbo.Site_SecurityGroup", "SiteId", "dbo.Site", "Id");
            AddForeignKey("dbo.Site_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup", "Id");
            AddForeignKey("dbo.Organization_Address", "OrganizationId", "dbo.Organization", "Id");
            AddForeignKey("dbo.Organization_Address", "AddressId", "dbo.Address", "Id");
            AddForeignKey("dbo.SecurityGroup_PermissionRecord", "PermissionRecordId", "dbo.PermissionRecord", "Id");
            AddForeignKey("dbo.SecurityGroup_PermissionRecord", "SecurityGroupId", "dbo.SecurityGroup", "Id");
            AddForeignKey("dbo.Report_SecurityGroup", "ReportId", "dbo.Report", "Id");
            AddForeignKey("dbo.Report_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup", "Id");
            AddForeignKey("dbo.Visual_SecurityGroup", "VisualId", "dbo.Visual", "Id");
            AddForeignKey("dbo.Visual_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup", "Id");
            AddForeignKey("dbo.Company_Address", "CompanyId", "dbo.Company", "Id");
            AddForeignKey("dbo.Company_Address", "AddressId", "dbo.Address", "Id");
            AddForeignKey("dbo.PM_MeterEvent", "PreventiveMaintenanceId", "dbo.PreventiveMaintenance", "Id");
            AddForeignKey("dbo.PM_MeterEvent", "MeterEventId", "dbo.MeterEvent", "Id");
            AddForeignKey("dbo.Team_Technician", "TeamId", "dbo.Team", "Id");
            AddForeignKey("dbo.Team_Technician", "TechnicianId", "dbo.Technician", "Id");
            AddForeignKey("dbo.ActivityLog", "UserId", "dbo.User", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ActivityLog", "UserId", "dbo.User");
            DropForeignKey("dbo.Team_Technician", "TechnicianId", "dbo.Technician");
            DropForeignKey("dbo.Team_Technician", "TeamId", "dbo.Team");
            DropForeignKey("dbo.PM_MeterEvent", "MeterEventId", "dbo.MeterEvent");
            DropForeignKey("dbo.PM_MeterEvent", "PreventiveMaintenanceId", "dbo.PreventiveMaintenance");
            DropForeignKey("dbo.Company_Address", "AddressId", "dbo.Address");
            DropForeignKey("dbo.Company_Address", "CompanyId", "dbo.Company");
            DropForeignKey("dbo.Visual_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.Visual_SecurityGroup", "VisualId", "dbo.Visual");
            DropForeignKey("dbo.Report_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.Report_SecurityGroup", "ReportId", "dbo.Report");
            DropForeignKey("dbo.SecurityGroup_PermissionRecord", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.SecurityGroup_PermissionRecord", "PermissionRecordId", "dbo.PermissionRecord");
            DropForeignKey("dbo.Organization_Address", "AddressId", "dbo.Address");
            DropForeignKey("dbo.Organization_Address", "OrganizationId", "dbo.Organization");
            DropForeignKey("dbo.Site_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup");
            DropForeignKey("dbo.Site_SecurityGroup", "SiteId", "dbo.Site");
            DropForeignKey("dbo.Site_Address", "AddressId", "dbo.Address");
            DropForeignKey("dbo.Site_Address", "SiteId", "dbo.Site");
            DropForeignKey("dbo.Assignment_User", "UserId", "dbo.User");
            DropForeignKey("dbo.Assignment_User", "AssignmentId", "dbo.Assignment");
            DropForeignKey("dbo.SecurityGroup_User", "UserId", "dbo.User");
            DropForeignKey("dbo.SecurityGroup_User", "SecurityGroupId", "dbo.SecurityGroup");
            AlterColumn("dbo.WorkflowInstance", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkflowInstance", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkflowInstance", "InstanceData", c => c.String(unicode: false));
            AlterColumn("dbo.WorkflowDefinitionVersion", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkflowDefinitionVersion", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkflowDefinitionVersion", "WorkflowXamlFileContent", c => c.String(unicode: false));
            AlterColumn("dbo.WorkflowDefinition", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkflowDefinition", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssignmentHistory", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssignmentHistory", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssignmentHistory", "DueDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssignmentHistory", "ExpectedStartDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssignmentGroupUser", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssignmentGroupUser", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssignmentGroup", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssignmentGroup", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Script", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Script", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Script", "SourceCode", c => c.String(unicode: false));
            AlterColumn("dbo.Log", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Log", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Log", "CreatedOnUtc", c => c.DateTime(nullable: false, precision: 0));
            AlterColumn("dbo.Log", "FullMessage", c => c.String(unicode: false));
            AlterColumn("dbo.Log", "ShortMessage", c => c.String(nullable: false, unicode: false));
            AlterColumn("dbo.ActivityLogType", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ActivityLogType", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ActivityLog", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ActivityLog", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UnitConversion", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UnitConversion", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Transfer", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Transfer", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Transfer", "TransferDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.TransferItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.TransferItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Return", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Return", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Return", "ReturnDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ReturnItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ReturnItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Receipt", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Receipt", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Receipt", "ReceiptDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ReceiptItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ReceiptItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ReceiptItem", "ExpiryDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Issue", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Issue", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Issue", "IssueDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.IssueItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.IssueItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PhysicalCountItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PhysicalCountItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PhysicalCount", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PhysicalCount", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PhysicalCount", "PhysicalCountDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Adjust", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Adjust", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Adjust", "AdjustDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AdjustItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AdjustItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorReservation", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorReservation", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ImportProfile", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ImportProfile", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ImportProfile", "LastRunEndDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ImportProfile", "LastRunStartDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ImportProfile", "EntityType", c => c.String(unicode: false));
            AlterColumn("dbo.UserDashboardVisual", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UserDashboardVisual", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UserDashboard", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UserDashboard", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Setting", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Setting", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MessageTemplate", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MessageTemplate", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MessageTemplate", "EmailBodyTemplate", c => c.String(unicode: false));
            AlterColumn("dbo.Message", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Message", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Message", "Errors", c => c.String(unicode: false));
            AlterColumn("dbo.Message", "CCRecipientNames", c => c.String(unicode: false));
            AlterColumn("dbo.Message", "RecipientNames", c => c.String(unicode: false));
            AlterColumn("dbo.Message", "CCRecipients", c => c.String(unicode: false));
            AlterColumn("dbo.Message", "Recipients", c => c.String(unicode: false));
            AlterColumn("dbo.Message", "Subject", c => c.String(unicode: false));
            AlterColumn("dbo.Message", "Messages", c => c.String(unicode: false));
            AlterColumn("dbo.Message", "SentDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Picture", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Picture", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Comment", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Comment", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.EntityAttachment", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.EntityAttachment", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Attachment", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Attachment", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AutoNumber", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AutoNumber", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AutoNumber", "FormatString", c => c.String(unicode: false));
            AlterColumn("dbo.AuditTrail", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AuditTrail", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AuditTrail", "LogXml", c => c.String(unicode: false));
            AlterColumn("dbo.AuditTrail", "Date", c => c.DateTime(nullable: false, precision: 0));
            AlterColumn("dbo.AuditEntityConfiguration", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AuditEntityConfiguration", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.EntityAttribute", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.EntityAttribute", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Attribute", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Attribute", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetStatusHistory", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetStatusHistory", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetStatusHistory", "ChangedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Currency", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Currency", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMTask", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMTask", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMServiceItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMServiceItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMMiscCost", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMMiscCost", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMMeterFrequency", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMMeterFrequency", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMLabor", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMLabor", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PMItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderTask", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderTask", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderTask", "CompletedDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ServiceItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ServiceItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderServiceItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderServiceItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderMiscCost", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderMiscCost", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ShiftPattern", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ShiftPattern", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ShiftPattern", "EndTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ShiftPattern", "StartTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Shift", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Shift", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.CalendarNonWorking", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.CalendarNonWorking", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.CalendarNonWorking", "NonWorkingDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Calendar", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Calendar", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Technician", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Technician", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Team", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Team", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Craft", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Craft", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderLabor", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderLabor", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorItemLog", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorItemLog", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorItemLog", "TransactionDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorItemLog", "BatchDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorItem", "ExpiryDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocatorItem", "BatchDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocator", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreLocator", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.StoreItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Store", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Store", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrderItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Task", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Task", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.TaskGroup", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.TaskGroup", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ServiceRequest", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ServiceRequest", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ServiceRequest", "RequestedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrder", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrder", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrder", "ActualEndDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrder", "ActualStartDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrder", "OnSiteDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrder", "DueDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrder", "ExpectedStartDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.WorkOrder", "RequestedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Reading", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Reading", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Reading", "DateOfReading", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PointMeterLineItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PointMeterLineItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PointMeterLineItem", "LastDateOfReading", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MeterLineItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MeterLineItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MeterGroup", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MeterGroup", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Point", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Point", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MeterEventHistory", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MeterEventHistory", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UnitOfMeasure", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UnitOfMeasure", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Meter", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Meter", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MeterEvent", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.MeterEvent", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Code", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Code", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PreventiveMaintenance", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PreventiveMaintenance", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PreventiveMaintenance", "TempWorkDueDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PreventiveMaintenance", "TempExpectedStartDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PreventiveMaintenance", "EndDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PreventiveMaintenance", "FirstWorkDueDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PreventiveMaintenance", "FirstWorkExpectedStartDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ContractTerm", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ContractTerm", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ContractPriceItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ContractPriceItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Contract", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Contract", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Contract", "EndDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Contract", "StartDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Contact", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Contact", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Company", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Company", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ItemGroup", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ItemGroup", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Item", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Item", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetSparePart", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetSparePart", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ValueItemCategory", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ValueItemCategory", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ValueItem", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ValueItem", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Location", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Location", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UserDevice", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UserDevice", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UserPasswordHistory", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.UserPasswordHistory", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.LocaleStringResource", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.LocaleStringResource", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.LocaleStringResource", "ResourceValue", c => c.String(nullable: false, unicode: false));
            AlterColumn("dbo.Language", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Language", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.VisualFilter", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.VisualFilter", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Visual", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Visual", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Visual", "Query", c => c.String(unicode: false));
            AlterColumn("dbo.Filter", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Filter", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Filter", "SqlQuery", c => c.String(unicode: false));
            AlterColumn("dbo.ReportFilter", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ReportFilter", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ReportColumn", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.ReportColumn", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Report", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Report", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Report", "Query", c => c.String(unicode: false));
            AlterColumn("dbo.Module", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Module", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.FeatureAction", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.FeatureAction", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Feature", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Feature", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PermissionRecord", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.PermissionRecord", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.SecurityGroup", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.SecurityGroup", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Organization", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Organization", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Site", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Site", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Assignment", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Assignment", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Assignment", "DueDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Assignment", "ExpectedStartDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.User", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.User", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.User", "LastApiRequest", c => c.DateTime(precision: 0));
            AlterColumn("dbo.User", "LastLoginTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.User", "BannedDateFrom", c => c.DateTime(precision: 0));
            AlterColumn("dbo.User", "PasswordLastChanged", c => c.DateTime(precision: 0));
            AlterColumn("dbo.User", "DateOfBirth", c => c.DateTime(precision: 0));
            AlterColumn("dbo.User", "PasswordSalt", c => c.String(unicode: false));
            AlterColumn("dbo.AssetLocationHistory", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetLocationHistory", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetLocationHistory", "ChangedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Asset", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Asset", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Asset", "WarrantyEndDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Asset", "WarrantyStartDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Asset", "InstallationDate", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetDowntime", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetDowntime", "CreatedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetDowntime", "ReportedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetDowntime", "EndDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.AssetDowntime", "StartDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Address", "ModifiedDateTime", c => c.DateTime(precision: 0));
            AlterColumn("dbo.Address", "CreatedDateTime", c => c.DateTime(precision: 0));
            AddForeignKey("dbo.ActivityLog", "UserId", "dbo.User", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Team_Technician", "TechnicianId", "dbo.Technician", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Team_Technician", "TeamId", "dbo.Team", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PM_MeterEvent", "MeterEventId", "dbo.MeterEvent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PM_MeterEvent", "PreventiveMaintenanceId", "dbo.PreventiveMaintenance", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Company_Address", "AddressId", "dbo.Address", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Company_Address", "CompanyId", "dbo.Company", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Visual_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Visual_SecurityGroup", "VisualId", "dbo.Visual", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Report_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Report_SecurityGroup", "ReportId", "dbo.Report", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SecurityGroup_PermissionRecord", "SecurityGroupId", "dbo.SecurityGroup", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SecurityGroup_PermissionRecord", "PermissionRecordId", "dbo.PermissionRecord", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Organization_Address", "AddressId", "dbo.Address", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Organization_Address", "OrganizationId", "dbo.Organization", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Site_SecurityGroup", "SecurityGroupId", "dbo.SecurityGroup", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Site_SecurityGroup", "SiteId", "dbo.Site", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Site_Address", "AddressId", "dbo.Address", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Site_Address", "SiteId", "dbo.Site", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Assignment_User", "UserId", "dbo.User", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Assignment_User", "AssignmentId", "dbo.Assignment", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SecurityGroup_User", "UserId", "dbo.User", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SecurityGroup_User", "SecurityGroupId", "dbo.SecurityGroup", "Id", cascadeDelete: true);
        }
    }
}
