// <auto-generated />
namespace NohaFMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_errorFieldinChequeDeposit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_errorFieldinChequeDeposit));
        
        string IMigrationMetadata.Id
        {
            get { return "202105270601449_add_errorFieldinChequeDeposit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
