// <auto-generated />
namespace NohaFMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class isDeletedMyReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isDeletedMyReport));
        
        string IMigrationMetadata.Id
        {
            get { return "202111081113304_isDeletedMyReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
