// <auto-generated />
namespace NohaFMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addHubCodeChequeDeposit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addHubCodeChequeDeposit));
        
        string IMigrationMetadata.Id
        {
            get { return "202105282115122_add-HubCode-ChequeDeposit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
