// <auto-generated />
namespace NohaFMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class instrumn_no : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(instrumn_no));
        
        string IMigrationMetadata.Id
        {
            get { return "202112141836591_instrumn_no"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
