// <auto-generated />
namespace NohaFMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Password_policy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Password_policy));
        
        string IMigrationMetadata.Id
        {
            get { return "202109290956041_Password_policy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
